# Olist E-Commerce Data Cleaning Project

## Project Overview

This project focuses on cleaning and preparing the Brazilian Olist E-Commerce dataset for further analysis and business intelligence reporting.

The objective is to improve data quality by identifying and correcting inconsistencies, handling missing values, removing duplicates, standardizing formats, and preparing datasets for future SQL, Power BI, and analytics projects.

---

### Business Objective

Reliable business insights depend on clean and accurate data.

This project aims to:

- Improve data quality
- Eliminate inconsistencies
- Handle missing values
- Standardize data formats
- Prepare datasets for downstream analytics
- Create analysis-ready datasets

The cleaned datasets will later support customer analytics, sales performance analysis, product insights, logistics reporting, and business intelligence dashboards.

In [80]:
# ===============================================
# PART 1
# STEP 1.1 - IMPORT LIBRARIES
# ===============================================

import pandas as pd
import numpy as np

# Display settings for better readability
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

print("Libraries successfully imported.")

Libraries successfully imported.

## Import Required Libraries

The following Python libraries are imported to support data cleaning and preprocessing tasks.

### Libraries Used

- Pandas
- NumPy
- OS

These libraries provide functionality for:

- Data loading
- Data inspection
- Data transformation
- Missing value handling
- Duplicate detection
- File management

In [81]:
# ===============================================
# STEP 1.2 - LOAD ALL DATASETS
# ===============================================

customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")
order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")
products = pd.read_csv("../data/raw/olist_products_dataset.csv")
sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")
reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
category_translation = pd.read_csv("../data/raw/product_category_name_translation.csv")

print("All datasets loaded successfully.")

All datasets loaded successfully.

## Load Datasets

The Olist dataset contains multiple related tables representing different aspects of the e-commerce business.

Datasets loaded include:

- Customers
- Orders
- Order Items
- Payments
- Products
- Sellers
- Reviews
- Product Category Translation

These datasets will be cleaned individually before being used in future analytics projects.

## Initial Data Inspection

Before cleaning, each dataset is inspected to understand:

- Number of records
- Number of columns
- Data types
- Missing values
- General structure

This step helps identify potential quality issues that require cleaning.

In [116]:
# ===============================================
# STEP 1.3 - STRUCTURAL PROFILING BEFORE CLEANING
# ===============================================

datasets = {
    "Customers": customers,
    "Orders": orders,
    "Order Items": order_items,
    "Payments": payments,
    "Products": products,
    "Sellers": sellers,
    "Reviews": reviews,
    "Category Translation": category_translation
}

for name, df in datasets.items():
    print("=" * 70)
    print(f"{name} Dataset BEFORE CLEANING")
    print("=" * 70)

    # Shape
    print("Shape:", df.shape)

    # Column names
    print("\nColumn Names:")
    print(df.columns.tolist())

    # Data types
    print("\nData Types:")
    print(df.dtypes)

    # Numerical summary
    print("\nNumerical Summary:")
    print(df.describe())

    print("\nFirst 5 Records:")
    display(df.head(5))

    print("\n\n")

======================================================================
Customers Dataset BEFORE CLEANING
======================================================================
Shape: (99441, 5)

Column Names:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Data Types:
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

Numerical Summary:
       customer_zip_code_prefix
count                  99441.00
mean                   35137.47
std                    29797.94
min                     1003.00
25%                    11347.00
50%                    24416.00
75%                    58900.00
max                    99990.00

First 5 Records:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

======================================================================
Orders Dataset BEFORE CLEANING
======================================================================
Shape: (99441, 12)

Column Names:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'delivery_delay_days', 'late_delivery', 'order_total_value', 'purchase_month']

Data Types:
order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
delivery_delay_days                       int64
late_delivery                             int64
order_total_value                       float64
purchase_month                        period[M]
dtype: object

Numerical Summary:
         order_purchase_timestamp           order_approved_at  \
count                       99441                       99441
mean   2017-12-31 08:43:12.776581  2017-12-31 19:07:21.164720
min           2016-09-04 21:15:19         2016-09-15 12:16:38
25%           2017-09-12 14:46:19         2017-09-12 21:55:13
50%           2018-01-18 23:04:36         2018-01-19 11:54:30
75%           2018-05-04 15:42:16         2018-05-04 23:50:21
max           2018-10-17 17:30:18         2018-10-17 17:30:18
std                           NaN                         NaN

      order_delivered_carrier_date order_delivered_customer_date  \
count                        99441                         99441
mean    2018-01-03 13:14:34.579358    2018-01-13 06:50:40.982221
min            2016-10-04 10:26:40           2016-09-30 00:00:00
25%            2017-09-14 20:19:00           2017-09-22 21:28:06
50%            2018-01-23 16:52:58           2018-02-01 19:34:49
75%            2018-05-08 08:51:00           2018-05-15 17:51:03
max            2018-10-17 17:30:18           2018-11-12 00:00:00
std                            NaN                           NaN

      order_estimated_delivery_date  delivery_delay_days  late_delivery  \
count                         99441             99441.00       99441.00
mean     2018-01-24 03:08:37.730111               -11.52           0.07
min             2016-09-30 00:00:00              -147.00           0.00
25%             2017-10-03 00:00:00               -17.00           0.00
50%             2018-02-15 00:00:00               -12.00           0.00
75%             2018-05-25 00:00:00                -7.00           0.00
max             2018-11-12 00:00:00               188.00           1.00
std                             NaN                10.23           0.25

       order_total_value
count           98666.00
mean              160.58
min                 9.59
25%                61.98
50%               105.29
75%               176.87
max             13664.08
std               220.47

First 5 Records:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,delivery_delay_days,late_delivery,order_total_value,purchase_month
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,-8,0,38.71,2017-10
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,-6,0,141.46,2018-07
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,-18,0,179.12,2018-08
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,-13,0,72.20,2017-11
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,-10,0,28.62,2018-02

======================================================================
Order Items Dataset BEFORE CLEANING
======================================================================
Shape: (112650, 8)

Column Names:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value', 'total_item_value']

Data Types:
order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
total_item_value              float64
dtype: object

Numerical Summary:
       order_item_id         shipping_limit_date     price  freight_value  \
count      112650.00                      112650 112650.00      112650.00
mean            1.20  2018-01-07 15:36:52.192685    120.65          19.99
min             1.00         2016-09-19 00:15:34      0.85           0.00
25%             1.00  2017-09-20 20:57:27.500000     39.90          13.08
50%             1.00         2018-01-26 13:59:35     74.99          16.26
75%             1.00  2018-05-10 14:34:00.750000    134.90          21.15
max            21.00         2020-04-09 22:35:08   6735.00         409.68
std             0.71                         NaN    183.63          15.81

       total_item_value
count         112650.00
mean             140.64
min                6.08
25%               55.22
50%               92.32
75%              157.94
max             6929.31
std              190.72

First 5 Records:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_item_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04

======================================================================
Payments Dataset BEFORE CLEANING
======================================================================
Shape: (103886, 5)

Column Names:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Data Types:
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

Numerical Summary:
       payment_sequential  payment_installments  payment_value
count           103886.00             103886.00      103886.00
mean                 1.09                  2.85         154.10
std                  0.71                  2.69         217.49
min                  1.00                  0.00           0.00
25%                  1.00                  1.00          56.79
50%                  1.00                  1.00         100.00
75%                  1.00                  4.00         171.84
max                 29.00                 24.00       13664.08

First 5 Records:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

======================================================================
Products Dataset BEFORE CLEANING
======================================================================
Shape: (32951, 9)

Column Names:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Data Types:
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

Numerical Summary:
       product_name_lenght  product_description_lenght  product_photos_qty  \
count             32341.00                    32341.00            32341.00
mean                 48.48                      771.50                2.19
std                  10.25                      635.12                1.74
min                   5.00                        4.00                1.00
25%                  42.00                      339.00                1.00
50%                  51.00                      595.00                1.00
75%                  57.00                      972.00                3.00
max                  76.00                     3992.00               20.00

       product_weight_g  product_length_cm  product_height_cm  \
count          32951.00           32951.00           32951.00
mean            2276.38              30.81              16.94
std             4281.93              16.91              13.64
min                0.00               7.00               2.00
25%              300.00              18.00               8.00
50%              700.00              25.00              13.00
75%             1900.00              38.00              21.00
max            40425.00             105.00             105.00

       product_width_cm
count          32951.00
mean              23.20
std               12.08
min                6.00
25%               15.00
50%               20.00
75%               30.00
max              118.00

First 5 Records:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.00,287.00,1.00,225.00,16.00,10.00,14.00
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.00,276.00,1.00,1000.00,30.00,18.00,20.00
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.00,250.00,1.00,154.00,18.00,9.00,15.00
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.00,261.00,1.00,371.00,26.00,4.00,26.00
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.00,402.00,4.00,625.00,20.00,17.00,13.00

======================================================================
Sellers Dataset BEFORE CLEANING
======================================================================
Shape: (3095, 4)

Column Names:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Data Types:
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

Numerical Summary:
       seller_zip_code_prefix
count                 3095.00
mean                 32291.06
std                  32713.45
min                   1001.00
25%                   7093.50
50%                  14940.00
75%                  64552.50
max                  99730.00

First 5 Records:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

======================================================================
Reviews Dataset BEFORE CLEANING
======================================================================
Shape: (99224, 7)

Column Names:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Data Types:
review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

Numerical Summary:
       review_score        review_creation_date     review_answer_timestamp
count      99224.00                       99224                       99224
mean           4.09  2018-01-12 20:49:23.948238  2018-01-16 00:23:56.977939
min            1.00         2016-10-02 00:00:00         2016-10-07 18:32:28
25%            4.00         2017-09-23 00:00:00  2017-09-27 01:53:27.250000
50%            5.00         2018-02-02 00:00:00  2018-02-04 22:41:47.500000
75%            5.00         2018-05-16 00:00:00  2018-05-20 12:11:21.500000
max            5.00         2018-08-31 00:00:00         2018-10-29 12:27:35
std            1.35                         NaN                         NaN

First 5 Records:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,No title provided,No comment provided,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,No title provided,No comment provided,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,No title provided,No comment provided,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,No title provided,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,No title provided,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

======================================================================
Category Translation Dataset BEFORE CLEANING
======================================================================
Shape: (74, 2)

Column Names:
['product_category_name', 'product_category_name_english']

Data Types:
product_category_name            str
product_category_name_english    str
dtype: object

Numerical Summary:
       product_category_name product_category_name_english
count                     74                            74
unique                    74                            74
top             beleza_saude                 health_beauty
freq                       1                             1

First 5 Records:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [117]:
# Summary statistics

for name, df in datasets.items():
    print(f"{name}: Rows = {df.shape[0]}, Columns = {df.shape[1]}")

Customers: Rows = 99441, Columns = 5
Orders: Rows = 99441, Columns = 12
Order Items: Rows = 112650, Columns = 8
Payments: Rows = 103886, Columns = 5
Products: Rows = 32951, Columns = 9
Sellers: Rows = 3095, Columns = 4
Reviews: Rows = 99224, Columns = 7
Category Translation: Rows = 74, Columns = 2

In [118]:
# =====================================================
# TASK 2.1 – PRIMARY KEY VALIDATION
# =====================================================

print("PRIMARY KEY VALIDATION\n")

print("Customers - customer_id unique:",
      customers['customer_id'].nunique() == len(customers))

print("Orders - order_id unique:",
      orders['order_id'].nunique() == len(orders))

print("Order Items - composite PK (order_id + order_item_id) unique:",
      order_items[['order_id','order_item_id']].drop_duplicates().shape[0] == len(order_items))

print("Payments - composite PK (order_id + payment_sequential) unique:",
      payments[['order_id','payment_sequential']].drop_duplicates().shape[0] == len(payments))

print("Products - product_id unique:",
      products['product_id'].nunique() == len(products))

print("Sellers - seller_id unique:",
      sellers['seller_id'].nunique() == len(sellers))

print("Reviews - composite PK (review_id + order_id) unique:",
      reviews[['review_id','order_id']].drop_duplicates().shape[0] == len(reviews))

print("Category Translation - product_category_name unique:",
      category_translation['product_category_name'].nunique() == len(category_translation))


# =====================================================
# 2.2 - FOREIGN KEY VALIDATION
# =====================================================

print("\nFOREIGN KEY VALIDATION\n")

print("Orders.customer_id exists in Customers:",
      orders['customer_id'].isin(customers['customer_id']).all())

print("Order Items.order_id exists in Orders:",
      order_items['order_id'].isin(orders['order_id']).all())

print("Order Items.product_id exists in Products:",
      order_items['product_id'].isin(products['product_id']).all())

print("Order Items.seller_id exists in Sellers:",
      order_items['seller_id'].isin(sellers['seller_id']).all())

print("Payments.order_id exists in Orders:",
      payments['order_id'].isin(orders['order_id']).all())

print("Reviews.order_id exists in Orders:",
      reviews['order_id'].isin(orders['order_id']).all())

print("Products.product_category_name exists in Category Translation:",
      products['product_category_name'].isin(category_translation['product_category_name']).all())


# =====================================================
# 2.3 - RELATIONSHIP VALIDATION (1:M CHECKS)
# =====================================================

print("\nRELATIONSHIP VALIDATION\n")

print("Customers → Orders (1:M):",
      orders['customer_id'].nunique() <= len(orders))

print("Orders → Order Items (1:M):",
      order_items['order_id'].nunique() <= len(order_items))

print("Orders → Payments (1:M):",
      payments['order_id'].nunique() <= len(payments))

print("Orders → Reviews (1:M) using composite PK:",
      reviews[['review_id','order_id']].drop_duplicates().shape[0] == len(reviews)
      and reviews['order_id'].nunique() <= len(reviews))

PRIMARY KEY VALIDATION

Customers - customer_id unique: True
Orders - order_id unique: True
Order Items - composite PK (order_id + order_item_id) unique: True
Payments - composite PK (order_id + payment_sequential) unique: True
Products - product_id unique: True
Sellers - seller_id unique: True
Reviews - composite PK (review_id + order_id) unique: True
Category Translation - product_category_name unique: True

FOREIGN KEY VALIDATION

Orders.customer_id exists in Customers: True
Order Items.order_id exists in Orders: True
Order Items.product_id exists in Products: True
Order Items.seller_id exists in Sellers: True
Payments.order_id exists in Orders: True
Reviews.order_id exists in Orders: True
Products.product_category_name exists in Category Translation: True

RELATIONSHIP VALIDATION

Customers → Orders (1:M): True
Orders → Order Items (1:M): True
Orders → Payments (1:M): True
Orders → Reviews (1:M) using composite PK: True

In [119]:
# 2.4 How many orders have more than one review?

multi_review_orders = reviews.groupby('order_id').size()
count_multi = (multi_review_orders > 1).sum()

print("Number of orders with multiple reviews:", count_multi)

Number of orders with multiple reviews: 547

## Missing Value Assessment

Missing values can reduce data quality and negatively impact future analysis.

This step identifies:

- Columns containing missing values
- Percentage of missing records
- Potential strategies for handling incomplete data

Appropriate actions will be taken depending on business relevance and data availability.

In [120]:
# =====================================================
# STEP 3.1 – MISSING VALUE ANALYSIS
# =====================================================

print("MISSING VALUE ANALYSIS\n")

for name, df in datasets.items():
    print("=" * 70)
    print(f"{name} Dataset")
    print("=" * 70)

    missing_count = df.isnull().sum()
    missing_percent = (df.isnull().sum() / len(df)) * 100

    missing_table = pd.DataFrame({
        "Missing Count": missing_count,
        "Missing %": missing_percent.round(2)
    })

    missing_table = missing_table[missing_table["Missing Count"] > 0]

    if len(missing_table) == 0:
        print("No missing values.\n")
    else:
        display(missing_table)

    print("\n")

MISSING VALUE ANALYSIS

======================================================================
Customers Dataset
======================================================================
No missing values.



======================================================================
Orders Dataset
======================================================================

                   Missing Count  Missing %
order_total_value            775       0.78

======================================================================
Order Items Dataset
======================================================================
No missing values.



======================================================================
Payments Dataset
======================================================================
No missing values.



======================================================================
Products Dataset
======================================================================

                            Missing Count  Missing %
product_name_lenght                   610       1.85
product_description_lenght            610       1.85
product_photos_qty                    610       1.85

======================================================================
Sellers Dataset
======================================================================
No missing values.



======================================================================
Reviews Dataset
======================================================================
No missing values.



======================================================================
Category Translation Dataset
======================================================================
No missing values.

In [121]:
# 3.1.1 Products Without Category Mapping

products_without_category = products[
    ~products["product_category_name"]
    .isin(category_translation["product_category_name"])
].copy()

print("=" * 60)
print("Products Without Category Mapping Analysis")
print("=" * 60)

# Total count
print("Total products without translation:", products_without_category.shape[0])

print("\nTop 10 unmapped categories:")
print(products_without_category["product_category_name"].value_counts().head(10))

============================================================
Products Without Category Mapping Analysis
============================================================
Total products without translation: 0

Top 10 unmapped categories:
Series([], Name: count, dtype: int64)

## Duplicate Record Detection

Duplicate records can distort analytical results and create misleading business insights.

This step identifies duplicated observations across the datasets and removes unnecessary duplicates while preserving valid business records.

In [122]:
# ===============================================
# 3.2 ROW DUPLICATES VALIDATION
# ===============================================

print("DATA DUPLICATION VALIDATION\n")

# Row duplicate check
datasets = {
    "Customers": customers,
    "Orders": orders,
    "Order Items": order_items,
    "Payments": payments,
    "Products": products,
    "Sellers": sellers,
    "Reviews": reviews,
    "Category Translation": category_translation
}

print("----- ROW DUPLICATE CHECK -----\n")

for name, df in datasets.items():
    duplicates = df.duplicated().sum()
    print(f"{name} - Duplicate Rows: {duplicates}")

print("\n")


# ===============================================
# 3.2.1 PRIMARY / COMPOSITE KEY DUPLICATE CHECK
# ===============================================

print("----- KEY DUPLICATE CHECK -----\n")

# Customers
print("Customers - customer_id duplicates:",
      customers['customer_id'].duplicated().sum())

# Orders
print("Orders - order_id duplicates:",
      orders['order_id'].duplicated().sum())

# Order Items (composite key)
print("Order Items - (order_id + order_item_id) duplicates:",
      order_items.duplicated(subset=['order_id','order_item_id']).sum())

# Payments (composite key)
print("Payments - (order_id + payment_sequential) duplicates:",
      payments.duplicated(subset=['order_id','payment_sequential']).sum())

# Products
print("Products - product_id duplicates:",
      products['product_id'].duplicated().sum())

# Sellers
print("Sellers - seller_id duplicates:",
      sellers['seller_id'].duplicated().sum())

# Reviews (composite key)
print("Reviews - (review_id + order_id) duplicates:",
      reviews.duplicated(subset=['review_id','order_id']).sum())

# Category translation
print("Category Translation - product_category_name duplicates:",
      category_translation['product_category_name'].duplicated().sum())

DATA DUPLICATION VALIDATION

----- ROW DUPLICATE CHECK -----

Customers - Duplicate Rows: 0
Orders - Duplicate Rows: 0
Order Items - Duplicate Rows: 0
Payments - Duplicate Rows: 0
Products - Duplicate Rows: 0
Sellers - Duplicate Rows: 0
Reviews - Duplicate Rows: 0
Category Translation - Duplicate Rows: 0


----- KEY DUPLICATE CHECK -----

Customers - customer_id duplicates: 0
Orders - order_id duplicates: 0
Order Items - (order_id + order_item_id) duplicates: 0
Payments - (order_id + payment_sequential) duplicates: 0
Products - product_id duplicates: 0
Sellers - seller_id duplicates: 0
Reviews - (review_id + order_id) duplicates: 0
Category Translation - product_category_name duplicates: 0

## Data Type Validation

Accurate data types are essential for analysis and reporting.

This step ensures that:

- Dates are stored as datetime values
- Numerical fields use appropriate numeric formats
- Text fields are correctly represented as strings

Correct data types improve analytical accuracy and processing efficiency.

In [123]:
# =====================================================
# STEP 3.3 – Verification For Appropriate Data Formats
# =====================================================

print("Verification For Appropriate Data Formats\n")

for name, df in datasets.items():
    print("=" * 60)
    print(name)
    print(df.dtypes)

Verification For Appropriate Data Formats

============================================================
Customers
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object
============================================================
Orders
order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
delivery_delay_days                       int64
late_delivery                             int64
order_total_value                       float64
purchase_month                        period[M]
dtype: object
============================================================
Order Items
order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
total_item_value              float64
dtype: object
============================================================
Payments
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object
============================================================
Products
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object
============================================================
Sellers
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object
============================================================
Reviews
review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object
============================================================
Category Translation
product_category_name            str
product_category_name_english    str
dtype: object

In [124]:
# 3.4 List of date columns per dataset
date_columns = {
    "Orders": [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ],
    "Order Items": ["shipping_limit_date"],
    "Reviews": ["review_creation_date", "review_answer_timestamp"]
}

for dataset_name, cols in date_columns.items():
    print("="*60)
    print(f"{dataset_name} Date Type Validation")
    print("="*60)

    df = datasets[dataset_name]

    for col in cols:
        print(f"{col}: {df[col].dtype}")

============================================================
Orders Date Type Validation
============================================================
order_purchase_timestamp: datetime64[us]
order_approved_at: datetime64[us]
order_delivered_carrier_date: datetime64[us]
order_delivered_customer_date: datetime64[us]
order_estimated_delivery_date: datetime64[us]
============================================================
Order Items Date Type Validation
============================================================
shipping_limit_date: datetime64[us]
============================================================
Reviews Date Type Validation
============================================================
review_creation_date: datetime64[us]
review_answer_timestamp: datetime64[us]

## Text Standardization

Text values are standardized to improve consistency across datasets.

Cleaning activities include:

- Removing extra spaces
- Converting text to lowercase where appropriate
- Standardizing category names
- Improving data consistency

In [125]:
# 3.5 Upper/Lower Case Standardisation Check

print("Unique States (Customers):")
print(customers["customer_state"].unique())

print("Unique States (Sellers):")
print(sellers["seller_state"].unique())

Unique States (Customers):
<StringArray>
['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA', 'MS', 'CE',
 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB', 'TO', 'PI', 'AC', 'SE',
 'RR']
Length: 27, dtype: str
Unique States (Sellers):
<StringArray>
['SP', 'RJ', 'PE', 'PR', 'GO', 'SC', 'BA', 'DF', 'RS', 'MG', 'RN', 'MT', 'CE',
 'PB', 'AC', 'ES', 'RO', 'PI', 'MS', 'SE', 'MA', 'AM', 'PA']
Length: 23, dtype: str

In [126]:
# 3.6 Incorrect Numeric Types

print(products.dtypes)

# Check if numeric columns contain unexpected strings
numeric_columns = [
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

for col in numeric_columns:
    print(f"{col} non-numeric values:",
          products[col].apply(lambda x: isinstance(x, str)).sum())

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object
product_weight_g non-numeric values: 0
product_length_cm non-numeric values: 0
product_height_cm non-numeric values: 0
product_width_cm non-numeric values: 0

In [127]:
# 3.7 Structural Integrity (Negative Prices / Invalid Values)

print("Negative Prices:",
      (order_items["price"] < 0).sum())

print("Negative Freight:",
      (order_items["freight_value"] < 0).sum())

print("Invalid Review Scores:",
      reviews[~reviews["review_score"].between(1,5)].shape[0])

Negative Prices: 0
Negative Freight: 0
Invalid Review Scores: 0

In [128]:
# 3.8 Referential Integrity
# Orders Without Order Items

orders_without_items = orders[
    ~orders["order_id"].isin(order_items["order_id"])
].copy()

print("=" * 60)
print("Orders Without Items Analysis")
print("=" * 60)

# Total count
print("Total Orders without items:", orders_without_items.shape[0])

print("\nBreakdown by order status:")
print(orders_without_items["order_status"].value_counts())

============================================================
Orders Without Items Analysis
============================================================
Total Orders without items: 775

Breakdown by order status:
order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [129]:
# =====================================================
# Task 4.1 – DATE CONVERSION
# =====================================================

# Orders date columns
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at'])
orders['order_delivered_carrier_date'] = pd.to_datetime(orders['order_delivered_carrier_date'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

# Order Items
order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'])

# Reviews
reviews['review_creation_date'] = pd.to_datetime(reviews['review_creation_date'])
reviews['review_answer_timestamp'] = pd.to_datetime(reviews['review_answer_timestamp'])

print("All date columns successfully converted.")

print(orders.dtypes)
print(order_items.dtypes)
print(reviews.dtypes)

All date columns successfully converted.
order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
delivery_delay_days                       int64
late_delivery                             int64
order_total_value                       float64
purchase_month                        period[M]
dtype: object
order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
total_item_value              float64
dtype: object
review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [130]:
# 4.1.1 Date Null Check

for dataset_name, cols in date_columns.items():
    df = datasets[dataset_name]
    print(f"\n{dataset_name} Date Null Check")

    for col in cols:
        print(f"{col} NaT count:", df[col].isna().sum())

Orders Date Null Check
order_purchase_timestamp NaT count: 0
order_approved_at NaT count: 0
order_delivered_carrier_date NaT count: 0
order_delivered_customer_date NaT count: 0
order_estimated_delivery_date NaT count: 0

Order Items Date Null Check
shipping_limit_date NaT count: 0

Reviews Date Null Check
review_creation_date NaT count: 0
review_answer_timestamp NaT count: 0

In [131]:
# 4.2 Imputation using logically preceding timestamps

orders["order_approved_at"] = orders["order_approved_at"].fillna(
    orders["order_purchase_timestamp"]
)

orders["order_delivered_carrier_date"] = orders["order_delivered_carrier_date"].fillna(
    orders["order_approved_at"]
)

orders["order_delivered_customer_date"] = orders["order_delivered_customer_date"].fillna(
    orders["order_estimated_delivery_date"]
)

In [132]:
# 4.2.1 Date Null Check

for dataset_name, cols in date_columns.items():
    df = datasets[dataset_name]
    print(f"\n{dataset_name} Date Null Check")

    for col in cols:
        print(f"{col} NaT count:", df[col].isna().sum())

Orders Date Null Check
order_purchase_timestamp NaT count: 0
order_approved_at NaT count: 0
order_delivered_carrier_date NaT count: 0
order_delivered_customer_date NaT count: 0
order_estimated_delivery_date NaT count: 0

Order Items Date Null Check
shipping_limit_date NaT count: 0

Reviews Date Null Check
review_creation_date NaT count: 0
review_answer_timestamp NaT count: 0

In [133]:
# 4.2.2 Imputation using descriptive placeholders.

reviews["review_comment_title"] = reviews["review_comment_title"].fillna("No title provided")

reviews["review_comment_message"] = reviews["review_comment_message"].fillna("No comment provided")

In [134]:
# 4.3 Category Cleaning & Translation Consistency

print("=" * 60)
print("Category Cleaning & Translation Update")
print("=" * 60)

# Step 1: Replace missing categories
products["product_category_name"] = (
    products["product_category_name"]
    .fillna("unknown")
)

# Step 2: Add missing categories to translation table
missing_categories = pd.DataFrame({
    "product_category_name": [
        "portateis_cozinha_e_preparadores_de_alimentos",
        "pc_gamer",
        "unknown"
    ],
    "product_category_name_english": [
        "portable_kitchen_food_processors",
        "pc_gamer",
        "unknown"
    ]
})

category_translation = pd.concat(
    [category_translation, missing_categories],
    ignore_index=True
)

# Step 3: Quick validation
print("Missing values in products:", products["product_category_name"].isna().sum())
print("Total categories in translation table:", category_translation.shape[0])

============================================================
Category Cleaning & Translation Update
============================================================
Missing values in products: 0
Total categories in translation table: 77

In [135]:
# 4.4 Handle Missing Product Attributes (Numeric)

print("=" * 60)
print("Handling Missing Product Attributes")
print("=" * 60)

numeric_columns = [
    'product_weight_g',
    'product_length_cm',
    'product_height_cm',
    'product_width_cm'
]

# Step 1: Fill missing values with median
products[numeric_columns] = products[numeric_columns].fillna(
    products[numeric_columns].median()
)

# Step 2: Validation check
print("\nRemaining missing values:")
print(products[numeric_columns].isnull().sum())

============================================================
Handling Missing Product Attributes
============================================================

Remaining missing values:
product_weight_g     0
product_length_cm    0
product_height_cm    0
product_width_cm     0
dtype: int64

In [136]:
# 4.5 Case & Space Check + Text Standardisation

print("=" * 60)
print("Text Quality Check & Standardisation")
print("=" * 60)

def check_and_clean(df, column):
    print(f"\nChecking {column}")

    # Check issues BEFORE cleaning
    stripped = df[column].str.strip()
    space_issues = (df[column] != stripped).sum()
    unique_before = df[column].nunique()

    print("Values with leading/trailing spaces:", space_issues)
    print("Unique values BEFORE cleaning:", unique_before)

    # Cleaning step (strip + lowercase)
    df[column] = df[column].str.strip().str.lower()

    # Check AFTER cleaning
    unique_after = df[column].nunique()
    print("Unique values AFTER cleaning:", unique_after)

# Apply to datasets
check_and_clean(customers, "customer_city")
check_and_clean(sellers, "seller_city")
check_and_clean(products, "product_category_name")

============================================================
Text Quality Check & Standardisation
============================================================

Checking customer_city
Values with leading/trailing spaces: 0
Unique values BEFORE cleaning: 4119
Unique values AFTER cleaning: 4119

Checking seller_city
Values with leading/trailing spaces: 0
Unique values BEFORE cleaning: 611
Unique values AFTER cleaning: 611

Checking product_category_name
Values with leading/trailing spaces: 0
Unique values BEFORE cleaning: 74
Unique values AFTER cleaning: 74

In [137]:
# =====================================================
# 4.6 – PRIMARY KEY AND FOREIGN KEY REVALIDATION
# =====================================================

print("PRIMARY KEY VALIDATION\n")

print("Customers - customer_id unique:",
      customers['customer_id'].nunique() == len(customers))

print("Orders - order_id unique:",
      orders['order_id'].nunique() == len(orders))

print("Order Items - composite PK (order_id + order_item_id) unique:",
      order_items[['order_id','order_item_id']].drop_duplicates().shape[0] == len(order_items))

print("Payments - composite PK (order_id + payment_sequential) unique:",
      payments[['order_id','payment_sequential']].drop_duplicates().shape[0] == len(payments))

print("Products - product_id unique:",
      products['product_id'].nunique() == len(products))

print("Sellers - seller_id unique:",
      sellers['seller_id'].nunique() == len(sellers))

print("Reviews - composite PK (review_id + order_id) unique:",
      reviews[['review_id','order_id']].drop_duplicates().shape[0] == len(reviews))

print("Category Translation - product_category_name unique:",
      category_translation['product_category_name'].nunique() == len(category_translation))


# =====================================================
# FOREIGN KEY VALIDATION
# =====================================================

print("\nFOREIGN KEY VALIDATION\n")

print("Orders.customer_id exists in Customers:",
      orders['customer_id'].isin(customers['customer_id']).all())

print("Order Items.order_id exists in Orders:",
      order_items['order_id'].isin(orders['order_id']).all())

print("Order Items.product_id exists in Products:",
      order_items['product_id'].isin(products['product_id']).all())

print("Order Items.seller_id exists in Sellers:",
      order_items['seller_id'].isin(sellers['seller_id']).all())

print("Payments.order_id exists in Orders:",
      payments['order_id'].isin(orders['order_id']).all())

print("Reviews.order_id exists in Orders:",
      reviews['order_id'].isin(orders['order_id']).all())

print("Products.product_category_name exists in Category Translation:",
      products['product_category_name'].isin(category_translation['product_category_name']).all())


# =====================================================
# RELATIONSHIP VALIDATION (1:M CHECKS)
# =====================================================

print("\nRELATIONSHIP VALIDATION\n")

print("Customers → Orders (1:M):",
      orders['customer_id'].nunique() <= len(orders))

print("Orders → Order Items (1:M):",
      order_items['order_id'].nunique() <= len(order_items))

print("Orders → Payments (1:M):",
      payments['order_id'].nunique() <= len(payments))

print("Orders → Reviews (1:M) using composite PK:",
      reviews[['review_id','order_id']].drop_duplicates().shape[0] == len(reviews)
      and reviews['order_id'].nunique() <= len(reviews))

PRIMARY KEY VALIDATION

Customers - customer_id unique: True
Orders - order_id unique: True
Order Items - composite PK (order_id + order_item_id) unique: True
Payments - composite PK (order_id + payment_sequential) unique: True
Products - product_id unique: True
Sellers - seller_id unique: True
Reviews - composite PK (review_id + order_id) unique: True
Category Translation - product_category_name unique: False

FOREIGN KEY VALIDATION

Orders.customer_id exists in Customers: True
Order Items.order_id exists in Orders: True
Order Items.product_id exists in Products: True
Order Items.seller_id exists in Sellers: True
Payments.order_id exists in Orders: True
Reviews.order_id exists in Orders: True
Products.product_category_name exists in Category Translation: True

RELATIONSHIP VALIDATION

Customers → Orders (1:M): True
Orders → Order Items (1:M): True
Orders → Payments (1:M): True
Orders → Reviews (1:M) using composite PK: True

In [138]:
# =====================================================
# 5.1 – LATE DELIVERY FLAG
# =====================================================

# Calculate delivery delay in days
orders['delivery_delay_days'] = (orders['order_delivered_customer_date'] - orders['order_estimated_delivery_date']).dt.days

# A late delivery occurs if actual delivery > estimated delivery
orders['late_delivery'] = orders['delivery_delay_days'].apply(lambda x: 1 if x > 0 else 0)

print("Late delivery counts:")
orders['late_delivery'].value_counts()

Late delivery counts:

late_delivery
0    92906
1     6535
Name: count, dtype: int64

In [139]:
# 5.2 – TOTAL ORDER VALUE

order_items['total_item_value'] = order_items['price'] + order_items['freight_value']

order_revenue = (
    order_items
    .groupby('order_id')['total_item_value']
    .sum()
    .reset_index()
)

order_revenue.rename(columns={'total_item_value': 'order_total_value'}, inplace=True)

# Prevent duplicate column issue
orders = orders.drop(columns=['order_total_value'], errors='ignore')

orders = orders.merge(order_revenue, on='order_id', how='left')

print("Sample Order Revenue:")
print(orders[['order_id','order_total_value']].head())

Sample Order Revenue:
                           order_id  order_total_value
0  e481f51cbdc54678b7cc49136f2d6af7              38.71
1  53cdb2fc8bc7dce0b6741e2150273451             141.46
2  47770eb9100c2d0c44946d9cf07ec65d             179.12
3  949d5b44dbf5de918fe9c16f97b45f8a              72.20
4  ad21c59c0840e6cb83a9ceb5573f8159              28.62

In [140]:
# =====================================================
# 5.3 – CUSTOMER LIFETIME VALUE
# =====================================================

customer_revenue = (
    orders
    .groupby('customer_id')['order_total_value']
    .sum()
    .reset_index()
)

customer_revenue.rename(columns={'order_total_value': 'customer_clv'}, inplace=True)

print("Top 5 Customers by CLV:")
customer_revenue.sort_values('customer_clv', ascending=False).head()

Top 5 Customers by CLV:

                            customer_id  customer_clv
8546   1617b1357756262bfa56ab541c47bc16      13664.08
91985  ec5b2ba62e574342386871631fafd3fc       7274.88
77522  c6e2731c5b391845f6800c97401a43a9       6929.31
95124  f48d464a0baaea338cb25f816991ab1f       6922.21
24771  3fd6777bbce08a352fddd04e4a7cc8f6       6726.66

In [141]:
# =====================================================
# 5.4 – PURCHASE FREQUENCY
# =====================================================

purchase_frequency = (
    orders
    .groupby('customer_id')['order_id']
    .count()
)

print("Average purchase frequency:",
      round(purchase_frequency.mean(), 2))

Average purchase frequency: 1.0

In [142]:
# =====================================================
# 5.5 – AVERAGE BASKET VALUE
# =====================================================

average_basket_value = orders['order_total_value'].mean()

print("Average Basket Value:", round(average_basket_value, 2))

Average Basket Value: 160.58

In [143]:
# =====================================================
# 5.6 – ITEMS PER ORDER
# =====================================================

items_per_order = (
    order_items
    .groupby('order_id')['order_item_id']
    .count()
)

print("Average items per order:",
      round(items_per_order.mean(), 2))

Average items per order: 1.14

In [144]:
# =====================================================
# 5.7 – REVENUE PER SELLER
# =====================================================

seller_revenue = (
    order_items
    .groupby('seller_id')['total_item_value']
    .sum()
    .reset_index()
)

seller_revenue.rename(columns={'total_item_value': 'seller_total_revenue'}, inplace=True)

print("Top 5 Sellers by Revenue:")
seller_revenue.sort_values('seller_total_revenue', ascending=False).head()

Top 5 Sellers by Revenue:

                             seller_id  seller_total_revenue
857   4869f7a5dfa277a7dca6462dcf3b52b2             249640.70
1535  7c67e1448b00f6e969d365cea6b010ab             239536.44
1013  53243585a1d6dc2643021fd1853d8905             235856.68
881   4a3ca9315b744ce9f8e9374361493884             235539.96
3024  fa1c13f2614d7b5c4749cbc52fecda94             204084.73

In [145]:
# =====================================================
# 5.8 – MONTHLY REVENUE TREND
# =====================================================

orders['purchase_month'] = orders['order_purchase_timestamp'].dt.to_period('M')

monthly_revenue = (
    orders
    .groupby('purchase_month')['order_total_value']
    .sum()
    .reset_index()
)

print("Monthly Revenue:")
monthly_revenue.head()

Monthly Revenue:

  purchase_month  order_total_value
0        2016-09             354.75
1        2016-10           56808.84
2        2016-12              19.62
3        2017-01          137188.49
4        2017-02          286280.62

In [146]:
# =====================================================
# 5.9 – MONTHLY ORDER COUNT
# =====================================================

monthly_order_count = (
    orders.groupby('purchase_month')['order_id']
    .count()
    .reset_index()
    .rename(columns={'order_id':'monthly_order_count'})
)

print("Monthly order count:")
monthly_order_count.head()

Monthly order count:

  purchase_month  monthly_order_count
0        2016-09                    4
1        2016-10                  324
2        2016-12                    1
3        2017-01                  800
4        2017-02                 1780

## Final Data Quality Checks

After cleaning, final validation checks are performed to confirm:

- Missing values are handled
- Duplicates are removed
- Data types are correct
- Data consistency has improved

The datasets are now suitable for analytics and business intelligence workflows.

In [149]:
# ===============================
# 6.0 AFTER CLEANING SUMMARY
# ===============================

datasets_clean = {
    "Orders": orders,
    "Order Items": order_items,
    "Customers": customers,
    "Products": products,
    "Sellers": sellers,
    "Payments": payments,
    "Reviews": reviews,
    "Category Translation": category_translation
}

for name, df in datasets_clean.items():
    print("\n" + "="*60)
    print(f"{name} - AFTER CLEANING")
    print("="*60)

    # Shape
    print("Shape:", df.shape)

    # Data types
    print("\nData Types:")
    print(df.dtypes)

    # Numerical summary
    print("\nNumerical Summary:")
    print(df.describe())

    # Categorical summary
    print("\nCategorical Summary:")
    print(df.describe(include='object'))

============================================================
Orders - AFTER CLEANING
============================================================
Shape: (99441, 12)

Data Types:
order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
delivery_delay_days                       int64
late_delivery                             int64
purchase_month                        period[M]
order_total_value                       float64
dtype: object

Numerical Summary:
         order_purchase_timestamp           order_approved_at  \
count                       99441                       99441
mean   2017-12-31 08:43:12.776581  2017-12-31 19:07:21.164720
min           2016-09-04 21:15:19         2016-09-15 12:16:38
25%           2017-09-12 14:46:19         2017-09-12 21:55:13
50%           2018-01-18 23:04:36         2018-01-19 11:54:30
75%           2018-05-04 15:42:16         2018-05-04 23:50:21
max           2018-10-17 17:30:18         2018-10-17 17:30:18
std                           NaN                         NaN

      order_delivered_carrier_date order_delivered_customer_date  \
count                        99441                         99441
mean    2018-01-03 13:14:34.579358    2018-01-13 06:50:40.982221
min            2016-10-04 10:26:40           2016-09-30 00:00:00
25%            2017-09-14 20:19:00           2017-09-22 21:28:06
50%            2018-01-23 16:52:58           2018-02-01 19:34:49
75%            2018-05-08 08:51:00           2018-05-15 17:51:03
max            2018-10-17 17:30:18           2018-11-12 00:00:00
std                            NaN                           NaN

      order_estimated_delivery_date  delivery_delay_days  late_delivery  \
count                         99441             99441.00       99441.00
mean     2018-01-24 03:08:37.730111               -11.52           0.07
min             2016-09-30 00:00:00              -147.00           0.00
25%             2017-10-03 00:00:00               -17.00           0.00
50%             2018-02-15 00:00:00               -12.00           0.00
75%             2018-05-25 00:00:00                -7.00           0.00
max             2018-11-12 00:00:00               188.00           1.00
std                             NaN                10.23           0.25

       order_total_value
count           98666.00
mean              160.58
min                 9.59
25%                61.98
50%               105.29
75%               176.87
max             13664.08
std               220.47

Categorical Summary:

C:\Users\fredm\AppData\Local\Temp\ipykernel_17340\1573995543.py:34: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include='object'))

                                order_id                       customer_id  \
count                              99441                             99441
unique                             99441                             99441
top     e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
freq                                   1                                 1

       order_status
count         99441
unique            8
top       delivered
freq          96478

============================================================
Order Items - AFTER CLEANING
============================================================
Shape: (112650, 8)

Data Types:
order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
total_item_value              float64
dtype: object

Numerical Summary:
       order_item_id         shipping_limit_date     price  freight_value  \
count      112650.00                      112650 112650.00      112650.00
mean            1.20  2018-01-07 15:36:52.192685    120.65          19.99
min             1.00         2016-09-19 00:15:34      0.85           0.00
25%             1.00  2017-09-20 20:57:27.500000     39.90          13.08
50%             1.00         2018-01-26 13:59:35     74.99          16.26
75%             1.00  2018-05-10 14:34:00.750000    134.90          21.15
max            21.00         2020-04-09 22:35:08   6735.00         409.68
std             0.71                         NaN    183.63          15.81

       total_item_value
count         112650.00
mean             140.64
min                6.08
25%               55.22
50%               92.32
75%              157.94
max             6929.31
std              190.72

Categorical Summary:
                                order_id                        product_id  \
count                             112650                            112650
unique                             98666                             32951
top     8272b63d03f5f79c56e9e4120aec44ef  aca2eb7d00ea1a7b8ebd4e68314663af
freq                                  21                               527

                               seller_id
count                             112650
unique                              3095
top     6560211a19b47992c3666cc44a7e94c0
freq                                2033

============================================================
Customers - AFTER CLEANING
============================================================
Shape: (99441, 5)

Data Types:
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

Numerical Summary:
       customer_zip_code_prefix
count                  99441.00
mean                   35137.47
std                    29797.94
min                     1003.00
25%                    11347.00
50%                    24416.00
75%                    58900.00
max                    99990.00

Categorical Summary:

C:\Users\fredm\AppData\Local\Temp\ipykernel_17340\1573995543.py:34: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include='object'))
C:\Users\fredm\AppData\Local\Temp\ipykernel_17340\1573995543.py:34: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include='object'))

                             customer_id                customer_unique_id  \
count                              99441                             99441
unique                             99441                             96096
top     06b8999e2fba1a1fbc88172c00ba8bc7  8d50f5eadf50201ccdcedfb9e2ac8455
freq                                   1                                17

       customer_city customer_state
count          99441          99441
unique          4119             27
top        sao paulo             SP
freq           15540          41746

============================================================
Products - AFTER CLEANING
============================================================
Shape: (32951, 9)

Data Types:
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

Numerical Summary:
       product_name_lenght  product_description_lenght  product_photos_qty  \
count             32341.00                    32341.00            32341.00
mean                 48.48                      771.50                2.19
std                  10.25                      635.12                1.74
min                   5.00                        4.00                1.00
25%                  42.00                      339.00                1.00
50%                  51.00                      595.00                1.00
75%                  57.00                      972.00                3.00
max                  76.00                     3992.00               20.00

       product_weight_g  product_length_cm  product_height_cm  \
count          32951.00           32951.00           32951.00
mean            2276.38              30.81              16.94
std             4281.93              16.91              13.64
min                0.00               7.00               2.00
25%              300.00              18.00               8.00
50%              700.00              25.00              13.00
75%             1900.00              38.00              21.00
max            40425.00             105.00             105.00

       product_width_cm
count          32951.00
mean              23.20
std               12.08
min                6.00
25%               15.00
50%               20.00
75%               30.00
max              118.00

Categorical Summary:
                              product_id product_category_name
count                              32951                 32951
unique                             32951                    74
top     1e9e8ef04dbcff4541ed26657ea517e5       cama_mesa_banho
freq                                   1                  3029

============================================================
Sellers - AFTER CLEANING
============================================================
Shape: (3095, 4)

Data Types:
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

Numerical Summary:
       seller_zip_code_prefix
count                 3095.00
mean                 32291.06
std                  32713.45
min                   1001.00
25%                   7093.50
50%                  14940.00
75%                  64552.50
max                  99730.00

Categorical Summary:
                               seller_id seller_city seller_state
count                               3095        3095         3095
unique                              3095         611           23
top     3442f8959a84dea7ee197c632cb2df15   sao paulo           SP
freq                                   1         694         1849

============================================================
Payments - AFTER CLEANING
============================================================
Shape: (103886, 5)

Data Types:
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

Numerical Summary:
       payment_sequential  payment_installments  payment_value
count           103886.00             103886.00      103886.00
mean                 1.09                  2.85         154.10
std                  0.71                  2.69         217.49
min                  1.00                  0.00           0.00
25%                  1.00                  1.00          56.79
50%                  1.00                  1.00         100.00
75%                  1.00                  4.00         171.84
max                 29.00                 24.00       13664.08

Categorical Summary:
                                order_id payment_type
count                             103886       103886
unique                             99440            5
top     fa65dad1b0e818e3ccc5cb0e39231352  credit_card
freq                                  29        76795

============================================================
Reviews - AFTER CLEANING
============================================================
Shape: (99224, 7)

Data Types:
review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

Numerical Summary:
       review_score        review_creation_date     review_answer_timestamp
count      99224.00                       99224                       99224
mean           4.09  2018-01-12 20:49:23.948238  2018-01-16 00:23:56.977939
min            1.00         2016-10-02 00:00:00         2016-10-07 18:32:28
25%            4.00         2017-09-23 00:00:00  2017-09-27 01:53:27.250000
50%            5.00         2018-02-02 00:00:00  2018-02-04 22:41:47.500000
75%            5.00         2018-05-16 00:00:00  2018-05-20 12:11:21.500000
max            5.00         2018-08-31 00:00:00         2018-10-29 12:27:35
std            1.35                         NaN                         NaN

Categorical Summary:

C:\Users\fredm\AppData\Local\Temp\ipykernel_17340\1573995543.py:34: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include='object'))
C:\Users\fredm\AppData\Local\Temp\ipykernel_17340\1573995543.py:34: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include='object'))
C:\Users\fredm\AppData\Local\Temp\ipykernel_17340\1573995543.py:34: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include='object'))
C:\Users\fredm\AppData\Local\Temp\ipykernel_17340\1573995543.py:34: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include='object'))

                               review_id                          order_id  \
count                              99224                             99224
unique                             98410                             98673
top     c444278834184f72b1484dfe47de7f97  c88b1d1b157a9999ce368f218a407141
freq                                   3                                 3

       review_comment_title review_comment_message
count                 99224                  99224
unique                 4528                  36160
top       No title provided    No comment provided
freq                  87656                  58247

============================================================
Category Translation - AFTER CLEANING
============================================================
Shape: (77, 2)

Data Types:
product_category_name            str
product_category_name_english    str
dtype: object

Numerical Summary:
                                product_category_name  \
count                                              77
unique                                             74
top     portateis_cozinha_e_preparadores_de_alimentos
freq                                                2

           product_category_name_english
count                                 77
unique                                74
top     portable_kitchen_food_processors
freq                                   2

Categorical Summary:
                                product_category_name  \
count                                              77
unique                                             74
top     portateis_cozinha_e_preparadores_de_alimentos
freq                                                2

           product_category_name_english
count                                 77
unique                                74
top     portable_kitchen_food_processors
freq                                   2

C:\Users\fredm\AppData\Local\Temp\ipykernel_17340\1573995543.py:34: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df.describe(include='object'))

In [150]:
# 6.1 Summary statistics

print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Payments:", payments.shape)
print("Products:", products.shape)
print("Sellers:", sellers.shape)
print("Reviews:", reviews.shape)
print("Category Translation:", category_translation.shape)

Customers: (99441, 5)
Orders: (99441, 12)
Order Items: (112650, 8)
Payments: (103886, 5)
Products: (32951, 9)
Sellers: (3095, 4)
Reviews: (99224, 7)
Category Translation: (77, 2)

## Export Cleaned Datasets

The cleaned datasets are exported to the `data/cleaned` folder.

These files serve as the foundation for future projects including:

- SQL Analysis
- Power BI Dashboards
- Customer Segmentation
- Sales Analytics
- Business Intelligence Reporting

In [151]:
# 6.2 Save cleaned datasets into data/cleaned folder

customers.to_csv("../data/cleaned/clean_customers.csv", index=False)
orders.to_csv("../data/cleaned/clean_orders.csv", index=False)
order_items.to_csv("../data/cleaned/clean_order_items.csv", index=False)
payments.to_csv("../data/cleaned/clean_payments.csv", index=False)
products.to_csv("../data/cleaned/clean_products.csv", index=False)
sellers.to_csv("../data/cleaned/clean_sellers.csv", index=False)
reviews.to_csv("../data/cleaned/clean_reviews.csv", index=False)
category_translation.to_csv("../data/cleaned/clean_category_translation.csv", index=False)

print("All cleaned CSV files saved to data/cleaned/")

All cleaned CSV files saved to data/cleaned/

# Project Conclusion

The Olist E-Commerce datasets were successfully cleaned and prepared for future analysis.

Key achievements include:

- Handling missing values
- Removing duplicates
- Standardizing formats
- Validating data types
- Creating analysis-ready datasets

The cleaned datasets provide a reliable foundation for advanced analytics, SQL projects, dashboard development, and business decision-making.

---

### Next Phase

The next stage of this project will focus on:

- SQL Data Analysis
- Power BI Dashboard Development
- Customer Behaviour Analysis
- Product Performance Analysis
- Sales and Revenue Reporting